services:
  - type: web
    name: idea-collector
    env: node
    region: singapore  # or oregon, frankfurt 등 원하는 지역
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        value: 0523unji
      - key: CLIENT_ORIGIN
        value: https://idea-collector-1-pjy2.onrender.com/  
    plan: free
    autoDeploy: true
